"""Auto-generated by langgraph-spec-toolkit — DO NOT EDIT BY HAND.

Regenerate with the `render_python` MCP tool after changing spec.yaml.
Source spec: simple_chatbot
"""

from langgraph.graph import StateGraph, START, END
from typing import Annotated, TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage
from . import nodes


class GraphState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]


def build_graph():
    workflow = StateGraph(GraphState)

    workflow.add_node('greet', nodes.greet)
    workflow.add_node('chatbot', nodes.chatbot)
    workflow.add_node('tools', nodes.call_tools)

    workflow.add_edge(START, 'greet')
    workflow.add_edge('greet', 'chatbot')
    workflow.add_edge('tools', 'chatbot')
    workflow.add_conditional_edges(
        'chatbot',
        nodes.route_after_chatbot,
        {
            'continue': 'tools',
            'end': END,
        },
    )

    return workflow.compile()
